### ISSUE TITLE
Help. Building llama.cpp Library

### ISSUE THREAD

**Issue by pavelprosto94** [netdur/llama_cpp_dart#2]
Please tell us in more detail how to compile **llama.cpp**?
Which files should I copy and where should I copy them(I didn't find any *.so files)?

I try do this:
```
cd ~/.pub-cache/hosted/pub.dev/llama_cpp_dart-0.0.4
git clone https://github.com/ggerganov/llama.cpp.git
mkdir build
cd build
cmake .. -DLLAMA_BLAS=ON -DLLAMA_BLAS_VENDOR=OpenBLAS
cmake --build . --config Release
```

**Comment by netdur** [comment]
what platform? generally add `-DBUILD_SHARED_LIBS=ON` to `cmake ..`

**Comment by pavelprosto94** [comment]
platform Linux

**Comment by pavelprosto94** [comment]
the compilation was successful and I received 2 files - libggml_shared.so and libllama.so
And to which directory should they be copied?

**Comment by netdur** [comment]
place libllama.so in root folder of your project

**Comment by pavelprosto94** [comment]
error
```
Launching lib/main.dart on Linux in debug mode...

(boris:88419): Gdk-CRITICAL **: 22:21:13.306: gdk_window_get_state: assertion 'GDK_IS_WINDOW (window)' failed
Connecting to VM Service at ws://127.0.0.1:42281/GRcPMlo5nE8=/ws
[ERROR:flutter/runtime/dart_isolate.cc(1097)] Unhandled exception:
Invalid argument(s): Failed to lookup symbol 'llama_backend_init': /home/prosto/Sync/Projects/Flutter/boris/build/linux/x64/debug/bundle/lib/libflutter_linux_gtk.so: undefined symbol: llama_backend_init
#0      DynamicLibrary.lookup (dart:ffi-patch/ffi_dynamic_library_patch.dart:33:70)
#1      llama_cpp._llama_backend_initPtr (package:llama_cpp_dart/src/llama_cpp.dart:10187:63)
#2      llama_cpp._llama_backend_initPtr (package:llama_cpp_dart/src/llama_cpp.dart)
#3      llama_cpp._llama_backend_init (package:llama_cpp_dart/src/llama_cpp.dart:10190:7)
#4      llama_cpp._llama_backend_init (package:llama_cpp_dart/src/llama_cpp.dart)
#5      llama_cpp.llama_backend_init (package:llama_cpp_dart/src/llama_cpp.dart:10181:12)
#6      new Llama (package:llama_cpp_dart/src/llama.dart:63:9)
#7      LlamaProcessor._modelIsolateEntryPoint.<anonymous closure> (package:llama_cpp_dart/src/llama_processor.dart:89:21)
#8      _RootZone.runUnaryGuarded (dart:async/zone.dart:1594:10)
#9      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#10     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#11     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:784:19)
#12     _StreamController._add (dart:async/stream_controller.dart:658:7)
#13     _StreamController.add (dart:async/stream_controller.dart:606:5)
#14     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
```

**Comment by netdur** [comment]
@pavelprosto94, instead of spending time figuring out where Dart searches for shared libraries, I've introduced a libraryPath property to the Llama class. This allows for setting the full path of the library directly.
`Llama. libraryPath = "...";`

**Comment by netdur** [comment]
@pavelprosto94, please feel free to reopen the issue if the proposed solution doesn't resolve your problem.

**Comment by danemadsen** [comment]
Hi @netdur 
You can build llama.cpp as a shared library as part of the dart build process, as i have done in maid:

https://github.com/Mobile-Artificial-Intelligence/maid

This works for Linux, Windows and Linux but not MacOS and IOS. I can help you implement this logic if you'd like. You package seems like it may be able to replace my own implementation.

**Comment by netdur** [comment]
@pavelprosto94 potentially v0.0.6 may resolve your issue.

**Comment by NavodPeiris** [comment]
@pavelprosto94 did you successfully build this project? could you overcome #33 ?

**Comment by Vinayak006** [comment]
@netdur, I have placed the libllama.so file at the root folder, but the build is getting failed with below error.
```
flutter run
Launching lib/main.dart on RMX1851 in debug mode...

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':llama_cpp_dart:configureCMakeDebug[arm64-v8a]'.
> [CXX1405] error when building with cmake using /home/kingkong/.pub-cache/hosted/pub.dev/llama_cpp_dart-0.0.7/src/CMakeLists.txt: -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Check for working C compiler: /home/kingkong/Android/Sdk/ndk/23.1.7779620/toolchains/llvm/prebuilt/linux-x86_64/bin/clang - skipped
  -- Detecting C compile features
  -- Detecting C compile features - done
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Check for working CXX compiler: /home/kingkong/Android/Sdk/ndk/23.1.7779620/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++ - skipped
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
  -- CMAKE_C_FLAGS: -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security  -DANDROID_ARM_NEON=TRUE -DANDROID_TOOLCHAIN=clang -DANDROID_ABI=arm64-v8a -DANDROID_PLATFORM=android-23
  -- Configuring incomplete, errors occurred!
  See also "/home/kingkong/.pub-cache/hosted/pub.dev/llama_cpp_dart-0.0.7/android/.cxx/Debug/713z563y/arm64-v8a/CMakeFiles/CMakeOutput.log".

  C++ build system [configure] failed while executing:
      /home/kingkong/Android/Sdk/cmake/3.18.1/bin/cmake \
        -H/home/kingkong/.pub-cache/hosted/pub.dev/llama_cpp_dart-0.0.7/src \
        -DCMAKE_SYSTEM_NAME=Android \
        -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
        -DCMAKE_SYSTEM_VERSION=23 \
        -DANDROID_PLATFORM=android-23 \
        -DANDROID_ABI=arm64-v8a \
        -DCMAKE_ANDROID_ARCH_ABI=arm64-v8a \
        -DANDROID_NDK=/home/kingkong/Android/Sdk/ndk/23.1.7779620 \
        -DCMAKE_ANDROID_NDK=/home/kingkong/Android/Sdk/ndk/23.1.7779620 \
        -DCMAKE_TOOLCHAIN_FILE=/home/kingkong/Android/Sdk/ndk/23.1.7779620/build/cmake/android.toolchain.cmake \
        -DCMAKE_MAKE_PROGRAM=/home/kingkong/Android/Sdk/cmake/3.18.1/bin/ninja \
        -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/home/kingkong/YAVAR/projects/llama_cpp_app/build/llama_cpp_dart/intermediates/cxx/Debug/713z563y/obj/arm64-v8a \
        -DCMAKE_RUNTIME_OUTPUT_DIRECTORY=/home/kingkong/YAVAR/projects/llama_cpp_app/build/llama_cpp_dart/intermediates/cxx/Debug/713z563y/obj/arm64-v8a \
        -DCMAKE_BUILD_TYPE=Debug \
        -B/home/kingkong/.pub-cache/hosted/pub.dev/llama_cpp_dart-0.0.7/android/.cxx/Debug/713z563y/arm64-v8a \
        -GNinja
    from /home/kingkong/.pub-cache/hosted/pub.dev/llama_cpp_dart-0.0.7/android
  CMake Warning (dev) in CMakeLists.txt:
    No project() command is present.  The top-level CMakeLists.txt file must
    contain a literal, direct call to the project() command.  Add a line of
    code such as

      project(ProjectName)

    near the top of the file, but after cmake_minimum_required().

    CMake is pretending there is a "project(Project)" command on the first
    line.
  This warning is for project developers.  Use -Wno-dev to suppress it.

  CMake Warning at /home/kingkong/Android/Sdk/ndk/23.1.7779620/build/cmake/android-legacy.toolchain.cmake:416 (message):
    An old version of CMake is being used that cannot automatically detect
    compiler attributes.  Compiler identification is being bypassed.  Some
    values may be wrong or missing.  Update to CMake 3.19 or newer to use
    CMake's built-in compiler identification.
  Call Stack (most recent call first):
    /home/kingkong/Android/Sdk/ndk/23.1.7779620/build/cmake/android.toolchain.cmake:55 (include)
    /home/kingkong/Android/Sdk/cmake/3.18.1/share/cmake-3.18/Modules/CMakeDetermineSystem.cmake:93 (include)


  CMake Warning at /home/kingkong/Android/Sdk/ndk/23.1.7779620/build/cmake/android-legacy.toolchain.cmake:416 (message):
    An old version of CMake is being used that cannot automatically detect
    compiler attributes.  Compiler identification is being bypassed.  Some
    values may be wrong or missing.  Update to CMake 3.19 or newer to use
    CMake's built-in compiler identification.
  Call Stack (most recent call first):
    /home/kingkong/Android/Sdk/ndk/23.1.7779620/build/cmake/android.toolchain.cmake:55 (include)
    /home/kingkong/.pub-cache/hosted/pub.dev/llama_cpp_dart-0.0.7/android/.cxx/Debug/713z563y/arm64-v8a/CMakeFiles/3.18.1-g262b901/CMakeSystem.cmake:6 (include)
    /home/kingkong/.pub-cache/hosted/pub.dev/llama_cpp_dart-0.0.7/android/.cxx/Debug/713z563y/arm64-v8a/CMakeFiles/CMakeTmp/CMakeLists.txt:2 (project)


  CMake Warning at /home/kingkong/Android/Sdk/ndk/23.1.7779620/build/cmake/android-legacy.toolchain.cmake:416 (message):
    An old version of CMake is being used that cannot automatically detect
    compiler attributes.  Compiler identification is being bypassed.  Some
    values may be wrong or missing.  Update to CMake 3.19 or newer to use
    CMake's built-in compiler identification.
  Call Stack (most recent call first):
    /home/kingkong/Android/Sdk/ndk/23.1.7779620/build/cmake/android.toolchain.cmake:55 (include)
    /home/kingkong/.pub-cache/hosted/pub.dev/llama_cpp_dart-0.0.7/android/.cxx/Debug/713z563y/arm64-v8a/CMakeFiles/3.18.1-g262b901/CMakeSystem.cmake:6 (include)
    /home/kingkong/.pub-cache/hosted/pub.dev/llama_cpp_dart-0.0.7/android/.cxx/Debug/713z563y/arm64-v8a/CMakeFiles/CMakeTmp/CMakeLists.txt:2 (project)


  CMake Error at CMakeLists.txt:16 (add_subdirectory):
    add_subdirectory given source "./llama.cpp" which is not an existing
    directory.


```

Any idea on how to fix this?

**Comment by Vinayak006** [comment]
> place libllama.so in root folder of your project

@netdur, Yeah I have placed it in root folder and also mentioned the librarypath as "/home/user/llama_cpp_app/libllama.so". But still I got Failed to load error.
```
Failed to load dynamic library 'libllama.so': dlopen failed: library "libggml.so" not found: needed by /data/app/~~vsx70-PCu9HEgN69Rg13NQ==/com.example.llama_cpp_app-pngGCil9UMpOP0g4TnVHSA==/base.apk!/lib/arm64-v8a/libllama.so in namespace classloader-namespace
```
